### ISSUE TITLE
Support CircleCI Orbs

### ISSUE THREAD

**Issue by masutaka** [masutaka/circleci-bundle-update-pr#71]
https://circleci.com/orbs/

**Comment by sue445** [comment]
Supports `circleci-bundle-update-pr` on my orb.

* https://github.com/sue445/circleci-ruby-orbs#bundle-update-pr
* https://sue445.hatenablog.com/entry/2018/11/18/145335 (ja)

Thank you for awesome gem.

**Comment by masutaka** [comment]
Thanks a lot!

I'll use it in [.circleci/config.yml](https://github.com/masutaka/circleci-bundle-update-pr/blob/master/.circleci/config.yml).

**Comment by masutaka** [comment]
In this repository, I changed my mind that it would be better to CI without using the orb.
